### Settings file
# This file is intended to contain specific internal parameters

# Global settings
global:
  exec_name: ${EXEC_NAME}
   
  logging:
    formatter:
      fmt: '%(asctime)s - %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
    level: INFO
    file: data/logs/${EXEC_NAME}.log

api:
  config:
    host: 0.0.0.0
    port: 80
    reload: True

  middleware:
    allow_origins:
      - "*"
    allow_credentials: True
    allow_methods:
      - "*"
    allow_headers:
      - "*"

  example:
    prefix: /example
    tags:
      - example
    endpoints:
      get:
        pipeline: pipeline_name
      post:
        pipeline: pipeline_name

chat:
  embedding_model: sentence-transformers/all-mpnet-base-v2
  collection_name: romeojuliet
  llm_model: stabilityai/stablelm-zephyr-3b
